### PR TITLE
Fixes #3 long descriptions

### LINKED ISSUE #3: Descriptions can be soooooooooooooo looooooooooooooooooooong
Like this: 

```
<Kramer> pharmbot beer me ipa
<pharmbot> Give this beer a try:
<pharmbot> Harpoon Brewery Harpoon IPA
<pharmbot> IPA - American
<pharmbot> We started brewing this beer as a summer seasonal in 1993.  There were some great IPAs out in the Pacific Northwest, but no local IPAs on the east coast.  We wanted to have a local IPA, so we brewed one.  People absolutely loved it, and so did we.  So we made it a year-round beer, and it’s now our bestselling beer and our flagship.
<pharmbot> Description: Since its introduction, Harpoon IPA has remained unique in its ability to balance hop bitterness with a strong malt backbone. Dry-hopped with Cascade hops, it has a floral hop aroma and a finish that is bitter (it is an IPA after all!) without being harsh or astringent. Combined with a malty sweetness and the fruity esters of our proprietary yeast, those hops create a beer that is wonderfully hoppy but clean and refreshing enough to
<pharmbot> enjoy a few of - and we hope you do.    
<Jake> I uh...
<Jake> Should probably fix that too...
<Kramer> lol
```

If only there was a better way....

### PR DESCRIPTION
**Pull request by jvarness**
Replaces those spammy descriptions with a URL to the website of the brewery.... If there is one anyways.

### CODE REVIEW

**Comment by jvarness** [comment]
@pcarn, @drkenyan +1?

**Comment by pcarn** [comment]
+1, does it work?

**Comment by jvarness** [comment]
Yea it works.

**Comment by jvarness** [comment]
It's far less spammy

**Comment by drtootsie** [comment]
+1

**Comment by jvarness** [comment]
Thanks guys!

**Pull request merged**
